export function initialState() {
  return {
    controll: {
      agent: {
        currentTab: 1,
        currentChannel: '999_1',
        isPopoverOpened: false,
      },
      customer: {
        currentChannel: '999_1',
        isPopoverOpened: false,
      },
    },
    agent: {
      id: 999,
      name: 'Master Yoda',
      avatar: '/img/avatar-yoda.jpg',
    },
    customers: [
      {
        id: 1,
        name: 'Princess Leia',
        avatar: '/img/avatar-leia.jpg',
      },
      {
        id: 2,
        name: 'Darth Vader Silva',
        avatar: '/img/avatar-vader.jpg',
      },
      {
        id: 4,
        name: 'Chewbacca',
        avatar: '/img/avatar-chewbacca.jpg',
      },
      {
        id: 3,
        name: 'Darth Maul',
        avatar: '/img/avatar-maul.jpg',
      },
    ],
    channels: {
      '999_1': {
        agent: {
          id: 999,
          isTyping: false,
        },
        customer: {
          id: 1,
          isTyping: false,
        },
        chats: [
          {
            id: 1,
            sender: 'customer',
            message: 'Hello, i need help',
            sentAt: '11:11:34',
            read: true,
            views: 0,
          },
          {
            id: 2,
            sender: 'agent',
            message: 'Hay, how can i help you ?',
            sentAt: '11:11:34',
            read: true,
            views: 0,
          },
          {
            id: 3,
            sender: 'customer',
            message: 'Hum...want an advice',
            sentAt: '11:11:34',
            read: true,
            views: 0,
          },
        ],
      },
      '999_2': {
        agent: {
          id: 999,
          isTyping: false,
        },
        customer: {
          id: 2,
          isTyping: false,
        },
        chats: [],
      },
    },
    emojis: [
      { title: 'smile', emoji: '😄' },
      { title: 'smiley', emoji: '😃' },
      { title: 'grinning', emoji: '😀' },
      { title: 'blush', emoji: '😊' },
      { title: 'wink', emoji: '😉' },
      { title: 'heart_eyes', emoji: '😍' },
      { title: 'kissing_heart', emoji: '😘' },
      { title: 'kissing_closed_eyes', emoji: '😚' },
      { title: 'kissing', emoji: '😗' },
      { title: 'kissing_smiling_eyes', emoji: '😙' },
      { title: 'stuck_out_tongue_winking_eye', emoji: '😜' },
      { title: 'stuck_out_tongue_closed_eyes', emoji: '😝' },
      { title: 'stuck_out_tongue', emoji: '😛' },
      { title: 'flushed', emoji: '😳' },
      { title: 'grin', emoji: '😁' },
      { title: 'pensive', emoji: '😔' },
      { title: 'relieved', emoji: '😌' },
      { title: 'unamused', emoji: '😒' },
      { title: 'disappointed', emoji: '😞' },
      { title: 'persevere', emoji: '😣' },
      { title: 'cry', emoji: '😢' },
      { title: 'joy', emoji: '😂' },
      { title: 'sob', emoji: '😭' },
      { title: 'sleepy', emoji: '😪' },
      { title: 'disappointed_relieved', emoji: '😥' },
      { title: 'cold_sweat', emoji: '😰' },
      { title: 'sweat_smile', emoji: '😅' },
      { title: 'sweat', emoji: '😓' },
      { title: 'weary', emoji: '😩' },
      { title: 'tired_face', emoji: '😫' },
      { title: 'fearful', emoji: '😨' },
      { title: 'scream', emoji: '😱' },
      { title: 'angry', emoji: '😠' },
      { title: 'rage', emoji: '😡' },
      { title: 'triumph', emoji: '😤' },
      { title: 'confounded', emoji: '😖' },
      { title: 'laughing', emoji: '😆' },
      { title: 'yum', emoji: '😋' },
      { title: 'mask', emoji: '😷' },
      { title: 'face_with_sunglasses', emoji: '😎' },
      { title: 'sleeping', emoji: '😴' },
      { title: 'dizzy_face', emoji: '😵' },
      { title: 'astonished', emoji: '😲' },
      { title: 'worried', emoji: '😟' },
      { title: 'frowning', emoji: '😦' },
      { title: 'anguished', emoji: '😧' },
      { title: 'imp', emoji: '👿' },
      { title: 'open_mouth', emoji: '😮' },
      { title: 'grimacing', emoji: '😬' },
      { title: 'neutral_face', emoji: '😐' },
      { title: 'confused', emoji: '😕' },
      { title: 'hushed', emoji: '😯' },
      { title: 'smirk', emoji: '😏' },
      { title: 'expressionless', emoji: '😑' },
      { title: 'slightly_frowning_face', emoji: '🙁' },
      { title: 'face_with_rolling_eyes', emoji: '🙄' },
      { title: 'thinking_face', emoji: '🤔' },
      { title: 'zipper-mouth_face', emoji: '🤐' },
      { title: 'face_with_thermometer', emoji: '🤒' },
      { title: 'face_with_head-bandage', emoji: '🤕' },
      { title: 'slightly_smiling_face', emoji: '🙂' },
      { title: 'upside-down_face', emoji: '🙃' },
      { title: 'money-mouth_face', emoji: '🤑' },
      { title: 'hugging_face', emoji: '🤗' },
      { title: 'nerd_face', emoji: '🤓' },
      { title: 'man_with_gua_pi_mao', emoji: '👲' },
      { title: 'man_with_turban', emoji: '👳' },
      { title: 'cop', emoji: '👮' },
      { title: 'construction_worker', emoji: '👷' },
      { title: 'guardsman', emoji: '💂' },
      { title: 'detective', emoji: '🕵' },
      { title: 'baby', emoji: '👶' },
      { title: 'boy', emoji: '👦' },
      { title: 'girl', emoji: '👧' },
      { title: 'man', emoji: '👨' },
      { title: 'woman', emoji: '👩' },
      { title: 'older_man', emoji: '👴' },
      { title: 'older_woman', emoji: '👵' },
      { title: 'person_with_blond_hair', emoji: '👱' },
      { title: 'angel', emoji: '👼' },
      { title: 'princess', emoji: '👸' },
      { title: 'smiley_cat', emoji: '😺' },
      { title: 'smile_cat', emoji: '😸' },
      { title: 'heart_eyes_cat', emoji: '😻' },
      { title: 'kissing_cat', emoji: '😽' },
      { title: 'smirk_cat', emoji: '😼' },
      { title: 'scream_cat', emoji: '🙀' },
      { title: 'crying_cat_face', emoji: '😿' },
      { title: 'joy_cat', emoji: '😹' },
      { title: 'pouting_cat', emoji: '😾' },
      { title: 'japanese_ogre', emoji: '👹' },
      { title: 'japanese_goblin', emoji: '👺' },
      { title: 'see_no_evil', emoji: '🙈' },
      { title: 'hear_no_evil', emoji: '🙉' },
      { title: 'speak_no_evil', emoji: '🙊' },
      { title: 'skull', emoji: '💀' },
      { title: 'alien', emoji: '👽' },
      { title: 'hankey', emoji: '💩' },
      { title: 'fire', emoji: '🔥' },
      { title: 'sparkles', emoji: '✨' },
      { title: 'star2', emoji: '🌟' },
      { title: 'dizzy', emoji: '💫' },
      { title: 'boom', emoji: '💥' },
      { title: 'anger', emoji: '💢' },
      { title: 'sweat_drops', emoji: '💦' },
      { title: 'droplet', emoji: '💧' },
      { title: 'zzz', emoji: '💤' },
      { title: 'dash', emoji: '💨' },
      { title: 'ear', emoji: '👂' },
      { title: 'eyes', emoji: '👀' },
      { title: 'nose', emoji: '👃' },
      { title: 'tongue', emoji: '👅' },
      { title: 'lips', emoji: '👄' },
      { title: 'thumbs_up', emoji: '👍' },
      { title: '-1', emoji: '👎' },
      { title: 'ok_hand', emoji: '👌' },
      { title: 'facepunch', emoji: '👊' },
      { title: 'fist', emoji: '✊' },
      { title: 'wave', emoji: '👋' },
      { title: 'hand', emoji: '✋' },
      { title: 'open_hands', emoji: '👐' },
      { title: 'point_up_2', emoji: '👆' },
      { title: 'point_down', emoji: '👇' },
      { title: 'point_right', emoji: '👉' },
      { title: 'point_left', emoji: '👈' },
      { title: 'sign_of_the_horns', emoji: '🤘' },
      { title: 'raised_hand_with_fingers_splayed', emoji: '🖐' },
      { title: 'vulcan_salute', emoji: '🖖' },
      { title: 'middle_finger', emoji: '🖕' },
      { title: 'raised_hands', emoji: '🙌' },
      { title: 'pray', emoji: '🙏' },
      { title: 'clap', emoji: '👏' },
      { title: 'muscle', emoji: '💪' },
      { title: 'walking', emoji: '🚶' },
      { title: 'runner', emoji: '🏃' },
      { title: 'person_lifting_weights', emoji: '🏋' },
      { title: 'person_golfing', emoji: '🏌' },
      { title: 'dancer', emoji: '💃' },
      { title: 'couple', emoji: '👫' },
      { title: 'family', emoji: '👪' },
      { title: 'couplekiss', emoji: '💏' },
      { title: 'couple_with_heart', emoji: '💑' },
      { title: 'dancers', emoji: '👯' },
      { title: 'ok_woman', emoji: '🙆' },
      { title: 'no_good', emoji: '🙅' },
      { title: 'information_desk_person', emoji: '💁' },
      { title: 'raising_hand', emoji: '🙋' },
      { title: 'massage', emoji: '💆' },
      { title: 'haircut', emoji: '💇' },
      { title: 'nail_care', emoji: '💅' },
      { title: 'bride_with_veil', emoji: '👰' },
      { title: 'person_with_pouting_face', emoji: '🙎' },
      { title: 'person_frowning', emoji: '🙍' },
      { title: 'bow', emoji: '🙇' },
      { title: 'tophat', emoji: '🎩' },
      { title: 'crown', emoji: '👑' },
      { title: 'womans_hat', emoji: '👒' },
      { title: 'athletic_shoe', emoji: '👟' },
      { title: 'mans_shoe', emoji: '👞' },
      { title: 'sandal', emoji: '👡' },
      { title: 'high_heel', emoji: '👠' },
      { title: 'boot', emoji: '👢' },
      { title: 'shirt', emoji: '👕' },
      { title: 'necktie', emoji: '👔' },
      { title: 'womans_clothes', emoji: '👚' },
      { title: 'dress', emoji: '👗' },
      { title: 'running_shirt_with_sash', emoji: '🎽' },
      { title: 'jeans', emoji: '👖' },
      { title: 'kimono', emoji: '👘' },
      { title: 'bikini', emoji: '👙' },
      { title: 'briefcase', emoji: '💼' },
      { title: 'handbag', emoji: '👜' },
      { title: 'pouch', emoji: '👝' },
      { title: 'purse', emoji: '👛' },
      { title: 'eyeglasses', emoji: '👓' },
      { title: 'ribbon', emoji: '🎀' },
      { title: 'closed_umbrella', emoji: '🌂' },
      { title: 'lipstick', emoji: '💄' },
      { title: 'yellow_heart', emoji: '💛' },
      { title: 'blue_heart', emoji: '💙' },
      { title: 'purple_heart', emoji: '💜' },
      { title: 'green_heart', emoji: '💚' },
      { title: 'broken_heart', emoji: '💔' },
      { title: 'heartpulse', emoji: '💗' },
      { title: 'heartbeat', emoji: '💓' },
      { title: 'two_hearts', emoji: '💕' },
      { title: 'sparkling_heart', emoji: '💖' },
      { title: 'revolving_hearts', emoji: '💞' },
      { title: 'cupid', emoji: '💘' },
      { title: 'love_letter', emoji: '💌' },
      { title: 'kiss', emoji: '💋' },
      { title: 'ring', emoji: '💍' },
      { title: 'gem', emoji: '💎' },
      { title: 'bust_in_silhouette', emoji: '👤' },
      { title: 'speech_balloon', emoji: '💬' },
      { title: 'footprints', emoji: '👣' },
      { title: 'robot_face', emoji: '🤖' },
      { title: 'eye', emoji: '👁' },
    ],
  }
}
